<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>kleversdk</RootNamespace>
    <AssemblyName>kleversdk</AssemblyName>
    <PackageId>kleversdk</PackageId>
    <PackageVersion>0.0.10</PackageVersion>
    <Authors>Klever</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Description>Klever.net is a SDK for KleverChain</Description>
    <PackageProjectUrl>https://github.com/klever-io/klever.net</PackageProjectUrl>
    <PackageTags>klever;kleverchain;blockchain</PackageTags>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.4.0" />
    <PackageReference Include="dotnetstandard-bip39" Version="1.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="core\Helper\" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="core\Helper\" />
  </ItemGroup>

</Project>
