<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>demo</RootNamespace>
    <AssemblyName>demo</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="smartContract\helloWorld.wasm" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\kleversdk\kleversdk.csproj" />
  </ItemGroup>

</Project>
